<?php defined('BASEPATH') OR exit('No direct script access allowed') ; ?>
#Nama, Obj, Lokasi, Icon, Lebar, Tinggi, lTitlebar, lResize, lModal, lFrame, class
["Dashboard", "dsh", "", "fa fa-dashboard"]
    ["About Me", "dshaboutme", "admin/dash/dshaboutme", "fa  fa-thumbs-o-up"]
    ["Dashboard", "dmain", "admin/dash/main", "fa fa-dashboard"]
["Master", "mst" , "" , "fa fa-fire"]
    ["Organisasi", "mstorg","","fa fa-bank"]
        ["Kantor Cabang", "mstcabang","admin/mst/mstcabang","fa fa-circle-o"]
        ["Golongan Unit", "mstgol_unit","admin/mst/mstgol_unit","fa fa-circle-o"]
        ["Golongan Jabatan", "mstgol_jabatan","admin/mst/mstgol_jabatan","fa fa-circle-o"]
    ["Master Surat", "mstsurat","","fa fa-envelope"]
        ["Master Jenis Surat", "mstsurat_jenis","admin/mst/mstsurat_jenis","fa fa-circle-o"]
        ["Master Sifat Surat", "mstsurat_sifat","admin/mst/mstsurat_sifat","fa fa-circle-o"]
["Tiket", "tc", "", "fa fa-envelope"]
    ["Penomoran Surat Keluar", "tcsurat_keluar","admin/tc/tcsurat_keluar","fa fa-circle-o"]
    ["Surat Masuk", "tcsurat_masuk","admin/tc/tcsurat_masuk","fa fa-circle-o"]
    ["M.02", "tcm02","","fa fa-circle-o"]
        ["Penarikan Anggaran", "tcm_anggaran","admin/tc/tcm_anggaran","fa fa-circle-o"]
    ["IKU", "tciku", "", "fa fa-circle-o"]
        ["Master IKU", "tciku_master","admin/tc/tciku_master","fa fa-circle-o"]    
        ["Form IKU", "tciku_form","admin/tc/tciku_form","fa fa-circle-o"]    
["Laporan", "rpt", "", "fa fa-folder-open"]
    ["Daftar Surat Masuk", "rptsuratmasuk","admin/rpt/rptsuratmasuk","fa fa-circle-o"]
["Utilities", "utlconf", "admin/config/utlconf","fa fa-flask"]
	#["Config", "config", "admin/config/config","fa fa-cogs"]
	#["Username", "con_user", "admin/config/username"]
	#["Username Level", "con_userlevel", "admin/config/username_lv"]
