<?php defined('BASEPATH') OR exit('No direct script access allowed') ; ?>
#Nama, Obj, Lokasi, Icon, Lebar, Tinggi, lTitlebar, lResize, lModal, lFrame, class
["Dashboard", "dash" , "" , "fa fa-dashboard"]
    ["Dashboard", "dmain", "admin/dash/main", "fa fa-dashboard"]
    ["PSBI Dashboard", "dpsbi", "admin/dash/dpsbi", "fa fa-dashboard"]
["Master", "mst" , "" , "fa fa-fire"]
    ["Organisasi", "mstorg","","fa fa-bank"]
        ["Golongan Unit", "mstgol_unit","admin/mst/mstgol_unit","fa fa-circle-o"]
        ["Golongan Jabatan", "mstgol_jabatan","admin/mst/mstgol_jabatan","fa fa-circle-o"]
    ["Master Dokumen", "mstsurat","","fa fa-envelope"]
        ["Master Jenis Dokumen", "mstsurat_jenis","admin/mst/mstsurat_jenis","fa fa-circle-o"]
        ["Master Sifat Dokumen", "mstsurat_sifat","admin/mst/mstsurat_sifat","fa fa-circle-o"]
        ["Upload Template Dokumen", "mstsurat_template","admin/mst/mstsurat_template","fa fa-circle-o"]
        ["Master Pencetakan Dokumen", "mstsurat_cetak","admin/mst/mstsurat_cetak","fa fa-circle-o"]
    ["Master Tahun Buku", "msttahun_buku","admin/mst/msttahun_buku","fa fa-circle-o"]
    ["Master PSBI", "mstpsbi", "", "fa fa-gg"]
        ["Master Lokasi PSBI", "mstpsbi_lokasi","admin/mst/mstpsbi_lokasi","fa fa-circle-o"]
        ["Master Golongan PSBI", "mstpsbi_golongan","admin/mst/mstpsbi_golongan","fa fa-circle-o"]
["Tiket", "tc", "", "fa fa-envelope"]
    ["Penomoran Dokumen", "tcsurat_keluar","admin/tc/tcsurat_keluar","fa fa-circle-o"]
    ["Dokumen Masuk", "tcsurat_masuk","admin/tc/tcsurat_masuk","fa fa-circle-o"]
    #["M.02", "tcm02","","fa fa-circle-o"]
    ["Memorandum (M.02)", "tcm_prinsip","admin/tc/tcm_prinsip","fa fa-circle-o"]
    ["IKU", "tciku", "", "fa fa-circle-o"]
        ["KONKIN", "tciku_master","admin/tc/tciku_master","fa fa-server"]    
        ["EKB", "tciku_form","admin/tc/tciku_form","fa fa-file-text-o"]    
    ["Penugasan", "tcwo", "", "fa fa-circle-o"]
        ["Penugasan", "tcwo_master","admin/tc/tcwo_master","fa fa-server"]    
        ["Ditugaskan", "tcwo_form","admin/tc/tcwo_form","fa fa-file-text-o"]   
    ["PSBI", "tcpsbi", "", "fa fa-gg"]
        ["Mutasi Anggaran", "tcpsbi_mutanggaran","admin/tc/tcpsbi_mutanggaran","fa fa-circle-o"]    
        ["Realisasi PSBI", "tcpsbi_realisasi","admin/tc/tcpsbi_realisasi","fa fa-circle-o"]    
["Laporan", "rpt", "", "fa fa-folder-open"]
    ["Daftar Dokumen Masuk", "rptsuratmasuk","admin/rpt/rptsuratmasuk","fa fa-circle-o"]
    ["Daftar Dokumen Keluar", "rptsurat_keluar","admin/rpt/rptsurat_keluar","fa fa-circle-o"]
    ["Memorandum (M.02)", "rptm02_prinsip","admin/rpt/rptm02_prinsip","fa fa-circle-o"]
    ["Penugasan", "rptwo", "", "fa fa-circle-o"]
        ["Daftar Penugasan", "rptwo","admin/rpt/rptwo","fa fa-briefcase"]    
    ["PSBI", "rptpsbi", "", "fa fa-gg"]
        ["Realisasi PSBI", "rptpsbi_realisasi","admin/rpt/rptpsbi_realisasi","fa fa-circle-o"]    
["Utilities", "utlconf", "admin/config/utlconf","fa fa-flask"]
["___________________________", "-", "",""]
["Ganti Password", "utlchangepassword", "admin/config/utlchangepassword","fa fa-unlock-alt"]
["Ganti Foto Profile", "utlchangepp", "admin/config/utlchangepp","fa fa-camera"]
